### ISSUE TITLE
Login fail after upgrade to v3.0.0 (please specify JIRA_BAS_URL)

### ISSUE THREAD

**Issue by cedmart1decath** [atlassian/gajira-login#36]
Run atlassian/gajira-login@v3
Error: Please specify JIRA_BASE_URL env
    at exec (/home/runner/work/_actions/atlassian/gajira-login/v3/dist/index.js:29722:43)
    at /home/runner/work/_actions/atlassian/gajira-login/v3/dist/index.js:29769:1
    at /home/runner/work/_actions/atlassian/gajira-login/v3/dist/index.js:29771:3
    at Object.<anonymous> (/home/runner/work/_actions/atlassian/gajira-login/v3/dist/index.js:29774:[12](https://github.com/dktunited/electronics-decathlon-connect-android-app/actions/runs/3533948691/jobs/5930242934#step:2:13))
    at Module._compile (node:internal/modules/cjs/loader:1101:[14](https://github.com/dktunited/electronics-decathlon-connect-android-app/actions/runs/3533948691/jobs/5930242934#step:2:15))
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[15](https://github.com/dktunited/electronics-decathlon-connect-android-app/actions/runs/3533948691/jobs/5930242934#step:2:16)3:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:[12](https://github.com/dktunited/electronics-decathlon-connect-android-app/actions/runs/3533948691/jobs/5930242934#step:2:13))
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Same yaml conf works in another action (it waa working when using v2)

    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3 # same with v3.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

**Comment by mboudreau** [comment]
We haven't changed any code around the validation of the environment variables, so this is surprising.  The logic is pretty simplistic:
```
if (!process.env.JIRA_BASE_URL) throw new Error('Please specify JIRA_BASE_URL env')
if (!process.env.JIRA_API_TOKEN) throw new Error('Please specify JIRA_API_TOKEN env')
if (!process.env.JIRA_USER_EMAIL) throw new Error('Please specify JIRA_USER_EMAIL env')
```

Essentially, if it's defined and not an empty string, it should pass.  Can you try setting the version to `v2.0.0` (the previous version) to see if it works then?  Our [action run seems to work fine using the latest](https://github.com/atlassian/gajira-login/actions/runs/3519871963/jobs/5900257659).

**Comment by cedmart1decath** [comment]
Damn not working with 2.0 either might be something wrong with my yaml then ! weird though because at some point it was working. I am closing this issue then.

**Comment by cedmart1decath** [comment]
After further investigation I found out that the problem come from the fact that dependabot does not have access to secrets !
